### ISSUE TITLE
Feature Requests and Bug Feedbacks

### ISSUE THREAD

**Issue by KanzakiYui** [Buizz/EUD-Editor-3#20]
There are couple of features I think could be beneficial for user and make the editor more handful.

1.  Allow edit **_Air Weapon_** under **_Unit_** tab (currently only allow edit Ground Weapon)

![image](https://user-images.githubusercontent.com/25272408/79695450-ed5e7900-8244-11ea-9750-0e228b49a6d0.png)

2.  Add **_Preview Image_** under **_Sprites_** and **_Images_** tab (not sure if it needs too much work?)

![image](https://user-images.githubusercontent.com/25272408/79695488-20a10800-8245-11ea-899e-365c9e743234.png)

3. The `Open as map editor` seems broken (using SC:R latest version)?

![image](https://user-images.githubusercontent.com/25272408/79695510-44fce480-8245-11ea-9f49-599cbc254d5a.png)

4. **Text color preview** is not the same as in game, maybe need adjust?

![image](https://user-images.githubusercontent.com/25272408/79695575-a0c76d80-8245-11ea-956b-d11ce5f375ed.png)

5. Those black placeholder icons seems will be updated using correct corresponding icon (e.g. unit icon), am I right?

![image](https://user-images.githubusercontent.com/25272408/79695638-fe5bba00-8245-11ea-9a08-ea87928beb83.png)

6. For **_Trigger Editor_**, can we show a list of all functions that `epScript` supports? No need description, just function name, params and returns will be perfect. I knew we can type some characters to see a short available list, but it might be beneficial to show a full list aside.

Just share my experience as an editor user, thanks! :) ❤️

**Comment by Buizz** [comment]
1. This problem cause from translation. In my language, display this image
![주석 2020-04-20 154427](https://user-images.githubusercontent.com/19189816/79721767-e6576980-831d-11ea-95c4-4955bce63ca7.png)
I will try to solve this.
2. preview image exist. Includes Remastered Graphics as well as Carbot Graphics.
![주석 2020-04-20 154730](https://user-images.githubusercontent.com/19189816/79721995-451ce300-831e-11ea-90ce-2cf838fa86f1.png)

3. I don't know what happen.

4. I'll check it.

5. You must select them.
![제목 없음](https://user-images.githubusercontent.com/19189816/79722169-87462480-831e-11ea-9f05-833fe8ac0f15.png)

**Comment by KanzakiYui** [comment]
@Buizz Thanks a lot, (2)(5)(6) are resolved now :) 👍

**Comment by KanzakiYui** [comment]
For (3), I guess it maybe still due to the translation issue? At least, when using latest SC:R and english language, when click that map icon, **_program encounter errors and stop running_**. FYI I am using Windows 10 :) 

For (4), I am pretty sure it's a quite common and historical problem, since **SCMD 2** (latest version) also has the very similar issue, which means the color in preview is not the same with in game, **_especially when mix multiple colors text into single sentence_** :)

**Comment by KanzakiYui** [comment]
Just found out some icons are missing (I am using **_Remastered_** icons)
![image](https://user-images.githubusercontent.com/25272408/79940961-2e1ae580-8431-11ea-9341-a9bdc1bf9855.png)

**Comment by Buizz** [comment]
Those buttons have no default icon.

**Comment by KanzakiYui** [comment]
Looks like (1) (2) (4) (5) issues are resolved, thanks so much!
(4) has some icon mismatched issue tho...
regarding (3), it will throw errors like:

![image](https://user-images.githubusercontent.com/25272408/81632163-95e0a280-93d7-11ea-8c97-9478f69fbdf9.png)

Seems like I needs link it to game file (even though already linked), or SCMD application(?)

**Comment by Buizz** [comment]
I think this problem is caused by language differences in the operating system.

https://github.com/Buizz/EUD-Editor-3/blob/master/EUD%20Editor%203/Module/Tools/WindowControl.vb
Line 249

It's a problem with this code. Is there any problem you know because it is related?

**Comment by KanzakiYui** [comment]
> Is there any problem you know because it is related?

Not sure what you mean but here is error log:
```
System.ComponentModel.Win32Exception (0x80004005): No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at EUD_Editor_3.WindowMenu.WindowMenus.ScmdOpen()
   at EUD_Editor_3.ProjectControl.Btn_scmd_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

But it seems not very helpful... but yeah, I guess it could be OS encoding issue :(
